language: generic
sudo: required
services:
  - docker

before_install:
 - docker build -t posija/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true posija/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-186810805992"
  bucket_path: "docker_react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY